### ISSUE TITLE
Gemalto Tokend problem on ElCapitain & Sierra

### ISSUE THREAD

**Issue by idelovski** [smartcardservices/smartcardservices#147]
Managed to build it and put it in /Library/Security/tokend as I have a working PKCS11 module (works from FireFox) but I can't make it to work from [Tokend](https://github.com/smartcardservices/smartcardservices/tree/master/Tokend).

Reading log files and other events in Console, my pkcs11 module is called from Tokend as I put the card in the reder. Method ::probe is called, it scans /usr/local/lib/pkcs11 and finds my module, then it calls GetSlotInfo, GetTokenInfo, everything works fine, return value is 500, but then the process terminates.

I have put extra line in Gemalto.cpp so terminate looks like this:

    static void terminate(int /*sig*/)
    {
      syslog (1, "---TOKEND--- Terminating .............");

      delete token;
      _exit(0);
    }

Then I can see in Console GemaltoToken::probe returning score 500 and then there's this line:
**> com.apple.SecurityServer[78]: token in reader ActivIdentity USB Reader V3 cannot be used (error 100002)**
And then immediately another line in Cnsole, Tokend terminates:
**> ---TOKEND--- Terminating .............**

Already tried with the driver found here: https://github.com/martinpaljak/osx-ccid-installer/releases

Any pointers? Does this Tokend work with latest MacOS versions?

igor

**Comment by LudovicRousseau** [comment]
It looks like error 100002 is ``kPOSIXErrorENOENT`` https://www.osstatus.com/search/results?platform=all&framework=all&search=100002

But I have no idea why it fails.

**Comment by idelovski** [comment]
Thanks, but I already knew it could be that. The same error as in this case: https://github.com/OpenSC/OpenSC.tokend/issues/27 - the third line in his example:

> token in reader Yubico Yubikey NEO OTP+U2F+CCID cannot be used (error 100002)

I have installed latest drivers from here (https://github.com/martinpaljak/osx-ccid-installer) and created links to every possible version of ifd-ccid dylibs but nothing made it work.

Is this Gemalto Tokend even supported any more? On this page: https://smartcardservices.github.io/installers/ I can find "The TokenD modules available for installation are: BELPIC, CAC, CACNG, JPKI and PIV, which have all been updated to build 50000 and..." but Gemalto (https://github.com/smartcardservices/smartcardservices/tree/master/Tokend/PKCS11) is not mentioned.

In Token.cpp, above Token::_probe() there is this comment:

//  (1) See if we support this token. Return zero if not.
//      Return a score if we do - the lower, the better. 1 beats everyone else.

But from several probe() implementations I can see they all assumed the higher the score, the better. Is there some kind of documentation for Tokend projects?

Igor

**Comment by idelovski** [comment]
Looks like I found the problem. The serial nimber, or tokenInfo.serialNumber I had from the call to C_GetTokenInfo had a slash character. Like, serial number "01234789/01".

Today I was playing with DTrance on my system trying to figure out what is going on. Turns out securityd is secured from snooping with dtrace but I managed to see it creates a file with exact name of my tokenUid. It is a second param of function probe and tokend module is supposed to put something meaningfull in there. The PKCS11 by Gemalto I'm using creates this uid like this:

    snprintf(tokenUid, TOKEND_MAX_UID, "Gemalto tokend (%.*s)", (int) sizeof(mCKTokenInfo.serialNumber), mCKTokenInfo.serialNumber);

End result was "Gemalto tokend (01234789/01)".

The file is created in /var/db/TokenCache/tokens. The folder is secured and I couldnt see whats's in there but just the fact that securityd is creating a file fith a slash character in its name seemed like asking for trouble. Turns out, it is exactly my problem.

**Comment by idelovski** [comment]
To wrap this up, first problem I had was related to the slash character inside the serial number. Original PKCS#11 module has /01 for the first slot and /02 for the next. Replacing it with dashes in tokenUid solved the problem.

Another issue was related to object attributes. In GemaltoRecord.cpp CKA_MODULUS attribue is used. Well, CKA_MODULUS in original PKCS#11 module has CK_UNAVAILABLE_INFORMATION and C_FindObjects() did not return anything. Calling C_FindObjectsInit() with only first attribute did the trick.
