### ISSUE TITLE
macOS v10.12 and v10.13 installers

### ISSUE THREAD

**Issue by marcelocecin** [smartcardservices/smartcardservices#148]
hi there

when macOS v10.12 and v10.13 installers are be available at https://smartcardservices.github.io/installers/ ?
![captura de tela 2017-07-27 as 06 39 48](https://user-images.githubusercontent.com/2955762/28664305-664f5404-7296-11e7-8e97-8559bd807587.png)

thank you

**Comment by LudovicRousseau** [comment]
You can get the 10.12 Sierra binary from https://github.com/smartcardservices/smartcardservices/releases/

See also https://github.com/smartcardservices/smartcardservices.github.io/pull/2

**Comment by hatchzo** [comment]
I could not install SmartCardServices2.1.2-OSX10.12.pkg. Just after opening the pkg file, the warning panel appears with " Could not open “Smart Card Services 2.1.2 [OSX 10.12].pkg” due to broken, need to put it in the trash".

**Comment by LudovicRousseau** [comment]
I have no problem with this file. Check your file is not corrupted.
I have:
```
$ shasum Smart*
1778435ac182dcf7b64c98473c30c5d4b856eb4e  Smart Card Services 2.1.2 [OSX 10.12].pkg
f5960259fdfd4deb51075847816c5c7e34ad0d96  SmartCardServices2.1.2-OSX10.12.zip
```
Note that you can't install the version for 10.12 on High Sierra (10.13).

**Comment by hatchzo** [comment]
Strange, My machine is Siera 10.12.6 and SHA checksum was exact same. But it is interrupted with this message (Sorry Japanese).
![2018-01-24 14 16 49](https://user-images.githubusercontent.com/8035011/35315735-5a36fa6e-0111-11e8-8108-3cb9ec1ff2a1.png)

**Comment by ryandesign** [comment]
On my Sierra Mac I get:

> The package was signed with a certificate that has expired. If you acquired this package recently, it may not be authentic. Do you want to continue with the installation anyway?

More detail shows it's the certificate of Shawn Geddis (6NSF8PH78P) which expired November 7, 2017. Other than that, the package opens fine for me. But maybe if your Gatekeeper settings are different than mine, the expired certificate could manifest the error you're seeing.
